In [269]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

In [270]:
df = pd.read_csv("../Data/health_cleaned.csv")
df.head()

,Gender,Smoking,Alcohol_Consumption,Exercise_Frequency,Blood_Pressure,Cholesterol_Level,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Medication_Use,Family_History,Illness,alcohol_missing_flag,medication_missing_flag,minor_smoking_flag,minor_alcohol_flag
0,Female,No,Moderate,Never,Normal,Borderline,High,90,16.6,119,3.6,143.6,Unknown,No,Yes,0,1,0,0
1,Other,Yes,Unknown,Never,Normal,Normal,Low,20,29.9,69,9.9,121.8,Unknown,Yes,No,1,1,0,0
2,Male,Yes,Heavy,Daily,High,High,Low,52,33.5,54,8.5,107.0,Unknown,Yes,Yes,0,1,0,0
3,Male,Unknown,Unknown,Daily,Normal,High,Low,15,20.3,72,9.5,92.1,Unknown,No,Yes,0,1,1,1
4,Male,No,Moderate,Often,High,High,Medium,60,36.0,58,4.4,113.6,Unknown,No,Yes,0,1,0,0

In [271]:
gender_dummies = pd.get_dummies(df['Gender'], prefix='gender', dummy_na=False).iloc[:,:-1].astype('int')
smoking_dummies = pd.get_dummies(df['Smoking'], prefix='smoking', dummy_na=False).astype('int')
Medication_Use_dummies = pd.get_dummies(df['Medication_Use'], prefix='Medication_Use', dummy_na=False).iloc[:,:-1].astype('int')
smoking_dummies = smoking_dummies.drop(columns=['smoking_Unknown'])
alcohol_dummies = pd.get_dummies(df['Alcohol_Consumption'], prefix='Alcohol_Consumption', dummy_na=False).iloc[:,:-1].astype('int')
Cholesterol_Level_dummies = pd.get_dummies(df['Cholesterol_Level'], prefix='Cholesterol_Level', dummy_na=False, drop_first=True).astype('int')
df = pd.concat([df, gender_dummies, smoking_dummies, Medication_Use_dummies, alcohol_dummies, Cholesterol_Level_dummies], axis=1)
df = df.drop(['Gender', 'Smoking', 'Medication_Use', 'Alcohol_Consumption', 'Cholesterol_Level'], axis=1)

In [272]:
Exercise_Frequency_map = {
    "Never":1,
    "Rarely":2,
    "Often":3,
    "Daily":4
}
df['Exercise_Frequency'] = df['Exercise_Frequency'].map(Exercise_Frequency_map)

Blood_Pressure_map = {
    "Low":1,
    "Normal":2,
    "High":3
}
df['Blood_Pressure'] = df['Blood_Pressure'].map(Blood_Pressure_map)

Stress_Level_map = {
    "Low":1,
    "Medium":2,
    "High":3
}
df['Stress_Level'] = df['Stress_Level'].map(Stress_Level_map)

In [273]:
le = LabelEncoder()
sel_col = df[['Family_History', 'Illness']]
for col in sel_col:
    df[col] = le.fit_transform(df[col])

In [274]:
df.head()

,Exercise_Frequency,Blood_Pressure,Stress_Level,Age,BMI,Heart_Rate,Sleep_Hours,Blood_Sugar_Level,Family_History,Illness,...,gender_Female,gender_Male,smoking_No,smoking_Yes,Medication_Use_Occasional,Medication_Use_Regular,Alcohol_Consumption_Heavy,Alcohol_Consumption_Moderate,Cholesterol_Level_High,Cholesterol_Level_Normal
0,1,2,3,90,16.6,119,3.6,143.6,0,1,...,1,0,1,0,0,0,0,1,0,0
1,1,2,1,20,29.9,69,9.9,121.8,1,0,...,0,0,0,1,0,0,0,0,0,1
2,4,3,1,52,33.5,54,8.5,107.0,1,1,...,0,1,0,1,0,0,1,0,1,0
3,4,2,1,15,20.3,72,9.5,92.1,0,1,...,0,1,0,0,0,0,0,0,1,0
4,3,3,2,60,36.0,58,4.4,113.6,0,1,...,0,1,1,0,0,0,0,1,1,0

In [275]:
df.to_csv("../Data/data_preprocessed.csv", index=False)